---
- hosts: "{{ inventory_group }}"
  gather_facts: no
  connection: local

  tasks:

  - debug:
      var: session_path

  - debug:
      msg: "session_dir: {{ session_path | dirname }}"

  - name: Create any missing directory(ies) for sessions.properties 
    ansible.builtin.file:
      path: "{{ session_path | dirname }}"
      state: directory
    delegate_to: localhost
    run_once: true
  
  - name: Ensure sessions.properties exists and is empty
    ansible.builtin.copy:
      dest: "{{ session_path }}"
      content: ""
    delegate_to: localhost
    run_once: true
    
  - name: Set session_id
    ansible.builtin.set_fact: 
      session_id: "{{ 'session.' + ( inventory_hostname | replace('.', '_') ) + '.' }}"
    delegate_to: localhost
  
  - name: Populate Session File
    ansible.builtin.blockinfile:
      path: "{{ session_path }}"
      block: |
        {{ [ session_id + 'type',      session_type              ] | join("=") }}
        {{ [ session_id + 'host',      inventory_hostname        ] | join("=") }}
        {{ [ session_id + 'user',      session_user              ] | join("=") }}
        {{   session_id + session_secret                                       }}
        {{ [ session_id + 'port',      ( session_port | string ) ] | join("=") }}
        {{ [ session_id + 'tmp',       session_tmp_dir           ] | join("=") }}
      insertafter: EOF
      marker: "# Host: {{ inventory_hostname }} - {mark}"
    delegate_to: localhost